config/routes.rb
Rails.application.routes.draw do
	root to: 'todos#index'

	resources :todos, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
	def index
		@todos = Todo.all
	end

	def new
		@todo = Todo.new
	end

	def create
		Todo.create(todo_params)
		redirect_to root_path
	end

	private
	  def todo_params
	    params.fetch(:todo, {}).permit(:title)
	  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/index.html.erb
<h1>Todos</h1>

<%= link_to "Create Todo", new_todo_path %>

<ul class="todos">
	<%= @todos.each do |todo| %>
		<li><%= todo.title %></li>
	<% end %>
</ul>

app/views/todos/new.html.erb
<%= form_for @todo do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>
	<%= f.submit "Submit" %>
<% end %>